### PR TITLE
Support Apple version of iCalendar

### PR DESCRIPTION
**Pull request by martingeorgiu**
To be honest, I'm really not sure, whether this should be merged as it might violate the standard on which this library is based. However, without these changes, I was not able to parse generated iCalendar from Apple Calendar. The better way might be to have some bool when parsing the String, whether to support Apple taste of iCalendar. Then people that need to support Apple Calendar can parse it without any issues, and everyone else will be happily using the standard.

### CODE REVIEW

**Comment by martingeorgiu** [comment]
Sorry for a bit messy PR, because it is based on the previous PR https://github.com/Enough-Software/enough_icalendar/pull/5

However, I didn't want to make a final solution as I wanted to know your take on this before.

**Comment by robert-virkus** [comment]
Hi Martin, removing validity checks may indeed not the best way to handle this. Is there a way how to recognize Apple Calendar formats apart from not being fully standards compliant?
Maybe we could detect that and that adjust the checking automatically? Of course, the user of the lib should be able to override this behavior, e.g. with setting a FormatChecking enum (strict, loose).
What do you think?

Maybe it helps if you could share some typical Apple formats here - or send them to me via robert-at-enough-dot-de.

Thanks,
  Robert

**Comment by martingeorgiu** [comment]
Yeah totally agree! I've created a new Apple calendar with which you can reproduce the bug. In fact, there are two issues with the final result. One is the incorrect timezones, but the other is that `X-APPLE-STRUCTURED-LOCATION` parameter, is breaking the parsing as well. I'm using this workaround for now, but when you would be adding some loose check, this should I believe be also included:

```dart
VComponent _getAppleVComponentFromString(String data) {
  final containsStandardCompliantLineBreaks = data.contains('\r\n');
  final foldedLines = containsStandardCompliantLineBreaks
      ? data.split('\r\n')
      : data.split('\n');
  final lines = VComponent.unfold(
    foldedLines,
    containsStandardCompliantLineBreaks: containsStandardCompliantLineBreaks,
  ).where((e) => !e.startsWith('X-')).toList();
  return VComponent.parseLines(lines);
}
```

[test-apple-calendar.ics.zip](https://github.com/Enough-Software/enough_icalendar/files/9654172/test-apple-calendar.ics.zip)

**Comment by robert-virkus** [comment]
Hey Martin, thanks for the example. Can you test parsing with the latest git version of enough_icalendar? 
I think the package can now parse your  invitation correctly.

**Comment by martingeorgiu** [comment]
Hello, sadly, it is still throwing following errors:

<details>

<summary>logs</summary>

```
No property implementation found for X-APPLE-CALENDAR-COLOR:#0E61B9FF
No property implementation found for X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-APPLE-MAPKIT-HANDLE=CAES6gIIrk0Qxofi3Z/fmujjARoSCVbY+FypC0lAEQAAAKi4zSxAIpgBCgdDemVjaGlhEgJDWhoGUHJhZ3VlKgZQcmFndWUyBlByYWd1ZToGMTE5IDAwQghQcmFndWUgMVIcbsOhbcSbc3TDrSBVIHN2YXTDqWhvIEppxZnDrVoEMzQvNGIhbsOhbcSbc3TDrSBVIHN2YXTDqWhvIEppxZnDrSAzNC80cg1QcmFndWUgQ2FzdGxligEIUHJhZ3VlIDEqDlByYcW+c2vDvSBocmFkMg1QcmFndWUgQ2FzdGxlMiFuw6FtxJtzdMOtIFUgc3ZhdMOpaG8gSmnFmcOtIDM0LzQyDTExOSAwMCBQcmFndWUyB0N6ZWNoaWE4L1ABWk0KJQjGh+Ldn9+a6OMBEhIJVtj4XKkLSUARAAAAqLjNLEAYrk2QAwGiHyMIxofi3Z/fmujjARoWCg5QcmHFvnNrw70gaHJhZBAAKgJlbg==;X-APPLE-RADIUS=141.2945906408928;X-TITLE="Pražský hrad
Prague Castle, náměstí U svatého Jiří 34/4, 119 00 Prague, Czechia":geo:50.091106,14.401799
Encountered unsupported parameter [X-APPLE-MAPKIT-HANDLE]
Encountered unsupported parameter [X-APPLE-RADIUS]
Encountered unsupported parameter [X-TITLE]
Unhandled exception:
FormatException: Invalid property: no colon : found in [Prague Castle, náměstí U svatého Jiří 34/4, 119 00 Prague, Czechia]
#0      Property._getIndex
package:enough_icalendar/src/properties.dart:106
#1      Property._getNameEndIndex
package:enough_icalendar/src/properties.dart:73
#2      Property._getName
package:enough_icalendar/src/properties.dart:114
#3      Property.parseProperty
package:enough_icalendar/src/properties.dart:247
#4      VComponent.parseLines
package:enough_icalendar/src/components.dart:208
#5      VComponent.parse
package:enough_icalendar/src/components.dart:180
#6      parseCal
package:ical_test/ical_test.dart:5
#7      main
bin/ical_test.dart:4
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

</details>

In your tests, the `.ics` I've provided is being parsed just fine?

**Comment by martingeorgiu** [comment]
Hi Robert, sadly, I'm still getting following error: 

<details>

<summary>logs</summary>

```
No property implementation found for X-APPLE-CALENDAR-COLOR:#0E61B9FF
No property implementation found for X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-APPLE-MAPKIT-HANDLE=CAES6gIIrk0Qxofi3Z/fmujjARoSCVbY+FypC0lAEQAAAKi4zSxAIpgBCgdDemVjaGlhEgJDWhoGUHJhZ3VlKgZQcmFndWUyBlByYWd1ZToGMTE5IDAwQghQcmFndWUgMVIcbsOhbcSbc3TDrSBVIHN2YXTDqWhvIEppxZnDrVoEMzQvNGIhbsOhbcSbc3TDrSBVIHN2YXTDqWhvIEppxZnDrSAzNC80cg1QcmFndWUgQ2FzdGxligEIUHJhZ3VlIDEqDlByYcW+c2vDvSBocmFkMg1QcmFndWUgQ2FzdGxlMiFuw6FtxJtzdMOtIFUgc3ZhdMOpaG8gSmnFmcOtIDM0LzQyDTExOSAwMCBQcmFndWUyB0N6ZWNoaWE4L1ABWk0KJQjGh+Ldn9+a6OMBEhIJVtj4XKkLSUARAAAAqLjNLEAYrk2QAwGiHyMIxofi3Z/fmujjARoWCg5QcmHFvnNrw70gaHJhZBAAKgJlbg==;X-APPLE-RADIUS=141.2945906408928;X-TITLE="Pražský hrad
Prague Castle, náměstí U svatého Jiří 34/4, 119 00 Prague, Czechia":geo:50.091106,14.401799
Encountered unsupported parameter [X-APPLE-MAPKIT-HANDLE]
Encountered unsupported parameter [X-APPLE-RADIUS]
Encountered unsupported parameter [X-TITLE]
Unhandled exception:
FormatException: Invalid property: no colon : found in [Prague Castle, náměstí U svatého Jiří 34/4, 119 00 Prague, Czechia]
#0      Property._getIndex
package:enough_icalendar/src/properties.dart:106
#1      Property._getNameEndIndex
package:enough_icalendar/src/properties.dart:73
#2      Property._getName
package:enough_icalendar/src/properties.dart:114
#3      Property.parseProperty
package:enough_icalendar/src/properties.dart:247
#4      VComponent.parseLines
package:enough_icalendar/src/components.dart:208
#5      VComponent.parse
package:enough_icalendar/src/components.dart:180
#6      parseCal
package:ical_test/ical_test.dart:5
#7      main
bin/ical_test.dart:4
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

</details>

I see that in your `apple_test.dart` you have a variable `_iCalendarTestData` with which the parser actually works. But when I try to load the file I've provided it still fails to parse.

**Comment by martingeorgiu** [comment]
Yay, it works now! Thanks a lot Robert!

**Comment by robert-virkus** [comment]
Thanks for confirming, I have now released v0.12.0 with your changes!

**Comment by martingeorgiu** [comment]
Hi Robert, I'm so sorry for misinforming you, however on most of my test Apple calendars, it now works flawlessly. But when I've run it on my main calendar, there are still two issues.

The first is there is an empty line in the middle of the `.ics`. This in fact was the original goal to fix with this PR. The second issue is still with the `X-APPLE-STRUCTURED-LOCATION`. I've cherry-picked both of the issues, and I'm sending you a new `.ics` file to test things out. Hopefully, there won't be needed any other changes. The way I'm parsing the calendars for now without any issues is using `martingeorgiu:feat/allowEmptyLines` and `_getAppleVComponentFromString()` method I've mentioned here https://github.com/Enough-Software/enough_icalendar/pull/6#issuecomment-1259252625

[test-apple-calendar.ics.zip](https://github.com/Enough-Software/enough_icalendar/files/9689889/test-apple-calendar.ics.zip)

**Comment by robert-virkus** [comment]
Thanks Martin,  I have integrated your changes, added some improvements and released v0.13.0.
Please check, if you still run into problems. Specificially, there should be no need to ignore any properties for Apple-originating invites, so please test without your custom `_getAppleVComponentFromString` method.

**Comment by martingeorgiu** [comment]
Cool, version `0.13.0` now works even with the main calendar I have used daily for many years. Thanks a lot, @robert-virkus for such great work!

**Comment by robert-virkus** [comment]
Glad that it works now, thanks for your report and support!

**Pull request merged**
